<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WebsiteColors extends Model
{
    protected $fillable     = ['element', 'attribute', 'value'];

    public const COLOR_SELECTIONS = [
        'general_section'           => [
            "active"                => true,
            "tab_title"             => "General Section",
            "elements"              => [
                [
                    "section_title"         => "Side Nav submenu Title",
                    "section_description"   => "This is the section on the side navigation menu",
                    "attr_default"          => ".zeynep .submenu-header > a",
                    "attr_hover"            => ".zeynep .submenu-header > a:hover",
                ],
                [
                    "section_title"         => "Side Nav links",
                    "section_description"   => "This is the section on the side navigation menu",
                    "attr_default"          => ".zeynep ul > li.has-submenu > a",
                    "attr_hover"            => ".zeynep ul > li.has-submenu > a:hover",
                ],
                [
                    "section_title"         => "Side Product links",
                    "section_description"   => "This is the section on the side navigation menu",
                    "attr_default"          => ".zeynep ul > li > a:not(.btn)",
                    "attr_hover"            => ".zeynep ul > li > a:not(.btn):hover",
                ],
            ],
        ],
        'header_section'            => [
            "active"                => false,
            "tab_title"             => "Header Section",
            "elements"              => [
                [
                    "section_title"         => "Search bar button",
                    "section_description"   => "This area controls the look of the search button in the header section",
                    "attr_default"          => "header .btn-search",
                    "attr_hover"            => "header .btn-search:hover",
                ],
                [
                    "section_title"         => "Site Navigation top menu",
                    "section_description"   => "This area controls the look of the site top menu colors",
                    "attr_default"          => ".site-navigation > ul > li, .site-navigation > ul > li > a",
                    "attr_hover"            => ".site-navigation > ul > li:hover, .site-navigation > ul > li > a:hover",
                ],
                [
                    "section_title"         => "Site Navigation dropdown menu",
                    "section_description"   => "This area controls the look of the site dropdown menu colors",
                    "attr_default"          => ".site-navigation > ul > li ul > li, .site-navigation > ul > li ul > li > a",
                    "attr_hover"            => ".site-navigation > ul > li  ul > li:hover, .site-navigation > ul > li  ul > li > a:hover",
                ],
            ],
        ],
        'pagebuilder_section'       => [
            "active"                => false,
            "tab_title"             => "Pagebuilder Section",
            "elements"              => [
                [
                    "section_title"         => "Pagebuilder tabs",
                    "section_description"   => "This section involves setting color themes for various tab items generated by the page-builder such as products under categories and child categories",
                    "attr_default"          => ".pagebuilder-content .nav .nav-item > a, .pagebuilder-content .nav .nav-item *",
                    "attr_hover"            => ".pagebuilder-content .nav .nav-item:hover *,.pagebuilder-content .nav .nav-item a:hover *",
                    "important_default"     => " ",
                    "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "Pagebuilder tabs Arrow",
                    "section_description"   => "This section involves setting color themes for tab arrow that shows which tab is active",
                    "attr_default"          => ".pagebuilder-content .nav-link-caret.active::after",
                    "attr_hover"            => ".pagebuilder-content .nav-link-caret.hover::after",
                    "attr_config"           => "border-bottom-color",
                    "attr_mono"             => true,
                ],
            ],
        ],
    ];

    // public function getColorSelectionsAttribute()
    // {
    //     return collect($this->COLOR_SELECTIONS);
    // }
}
