<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WebsiteColors extends Model
{
    protected $fillable     = ['element', 'attribute', 'value'];

    public const COLOR_SELECTIONS = [
        'jquery_sidebar_nav_menu_section'           => [
            "active"                => true,
            "tab_title"             => "jQuery/ SidebarNav Menu Section",
            "elements"              => [
                [
                    "section_title"         => "Website body section",
                    "section_description"   => "This color settings will affect entire website page contents so take care",
                    "attr_default"          => "body",
                    "attr_hover"            => "body:hover",
                ],
                [
                    "section_title"         => "Bookworm Side Nav submenu Title",
                    "section_description"   => "This is the section on the side navigation menu",
                    "attr_default"          => ".zeynep .submenu-header > a",
                    "attr_hover"            => ".zeynep .submenu-header > a:hover",
                ],
                [
                    "section_title"         => "Bookworm Side Nav links",
                    "section_description"   => "This is the section on the side navigation menu",
                    "attr_default"          => ".zeynep ul > li.has-submenu > a",
                    "attr_hover"            => ".zeynep ul > li.has-submenu > a:hover",
                ],
                [
                    "section_title"         => "Bookworm Side Product links",
                    "section_description"   => "This is the section on the side navigation menu",
                    "attr_default"          => ".zeynep ul > li > a:not(.btn)",
                    "attr_hover"            => ".zeynep ul > li > a:not(.btn):hover",
                ],
                [
                    "section_title"         => "jQuery Side Nav Section Title",
                    "section_description"   => "This is the section on the side navigation menu",
                    "attr_default"          => ".hc-offcanvas-nav .nav-content>.nav-close:first-child a.has-label",
                    "attr_hover"            => ".hc-offcanvas-nav .nav-content>.nav-close:first-child a.has-label:hover",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "jQuery Side Nav Section",
                    "section_description"   => "This is the section on the side navigation menu",
                    "attr_default"          => ".hc-offcanvas-nav .nav-container, .hc-offcanvas-nav .nav-wrapper, .hc-offcanvas-nav ul",
                    "attr_hover"            => ".hc-offcanvas-nav .nav-container, .hc-offcanvas-nav .nav-wrapper, .hc-offcanvas-nav ul:hover",
                ],
                [
                    "section_title"         => "jQuery Side Nav Links",
                    "section_description"   => "This is the section on the side navigation menu",
                    "attr_default"          => ".hc-offcanvas-nav .nav-item-link, .hc-offcanvas-nav li.nav-close a, .hc-offcanvas-nav .nav-back a, .hc-offcanvas-nav:not(.touch-device) li:not(.nav-item-custom) a:not([disabled]):hover",
                    "attr_hover"            => ".hc-offcanvas-nav .nav-item-link:hover, .hc-offcanvas-nav li.nav-close a:hover, .hc-offcanvas-nav .nav-back a:hover, .hc-offcanvas-nav:not(.touch-device) li:not(.nav-item-custom) a:not([disabled]):hover",
                ],
                [
                    "section_title"         => "jQuery Side Nav Links Arrows",
                    "section_description"   => "This is the section on the side navigation menu '>' elements",
                    "attr_default"          => ".hc-offcanvas-nav .nav-next span::before, .hc-offcanvas-nav .nav-back span::before",
                    "attr_hover"            => ".hc-offcanvas-nav .nav-next span::before, .hc-offcanvas-nav .nav-back span::before",
                    "attr_config"           => "border-top-color",
                    "attr_mono"             => true,
                ],
                [
                    "section_title"         => "jQuery Side Nav Links Arrows",
                    "section_description"   => "This is the section on the side navigation menu '>' elements",
                    "attr_default"          => ".hc-offcanvas-nav .nav-next span::before, .hc-offcanvas-nav .nav-back span::before",
                    "attr_hover"            => ".hc-offcanvas-nav .nav-next span::before, .hc-offcanvas-nav .nav-back span::before",
                    "attr_config"           => "border-left-color",
                    "attr_mono"             => true,
                ],
            ],
        ],
        'header_section'            => [
            "active"                => false,
            "tab_title"             => "All Headers Menus/Icons/Text/Search Section",
            "elements"              => [
                [
                    "section_title"         => "Website header section",
                    "section_description"   => "This color settings will affect all website header colors",
                    "attr_default"          => "#site-header, #site-header .masthead div:not(#sidebarAuthToggler, .font-size-2, #sidebarNavToggler1)",
                    "attr_hover"            => "#site-header:hover, #site-header .masthead div:not(#sidebarAuthToggler, .font-size-2, #sidebarNavToggler1):hover",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "Search bar button",
                    "section_description"   => "This area controls the look of the search button in the header section",
                    "attr_default"          => "#site-header .btn-search",
                    "attr_hover"            => "#site-header .btn-search:active, #site-header .btn-search:focus, #site-header .btn-search:hover",
                ],
                [
                    "section_title"         => "Header Inquiry form button",
                    "section_description"   => "This color settings will affect the product inquiry form trigger button located on website headers",
                    "attr_default"          => "#site-header :is(a, button)[data-target='#headerProductInquiryModal']",
                    "attr_hover"            => "#site-header :is(a, button)[data-target='#headerProductInquiryModal']:hover",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "Header Icons + Texts (Combined settings) SVG elements",
                    "section_description"   => "This color settings will affect a number of items on the website headers. This includes all lements of typ SVG",
                    "attr_default"          => "#sidebarNavToggler svg path, #sidebarAuthToggler *, #sidebarNavToggler1 *",
                    "attr_hover"            => "#sidebarNavToggler:hover svg path, #sidebarAuthToggler *:hover, #sidebarNavToggler1 *:hover",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "fill",
                ],
                [
                    "section_title"         => "Header Icons + Texts (Combined settings)",
                    "section_description"   => "This color settings will affect a number of items on the website headers. This may include account and cart buttons with their respective texts",
                    "attr_default"          => "#sidebarNavToggler svg path, #sidebarAuthToggler *, #sidebarNavToggler1 *",
                    "attr_hover"            => "#sidebarNavToggler:hover svg path, #sidebarAuthToggler:hover *, #sidebarNavToggler1:hover *",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "color",
                ],
                // [
                //     "section_title"         => "Search bar button border",
                //     "section_description"   => "Configure the border color for the top nav search button",
                //     "attr_default"          => "#site-header .btn-search",
                //     "attr_hover"            => "#site-header .btn-search",
                //     "important_default"     => " !important",
                //     "important_hover"       => " !important",
                //     "attr_config"           => "border-color",
                //     "attr_mono"             => true,
                // ],
                [
                    "section_title"         => "Site Navigation top menu",
                    "section_description"   => "This area controls the look of the site top menu colors",
                    "attr_default"          => ".site-navigation > ul > li, .site-navigation > ul > li > a",
                    "attr_hover"            => ".site-navigation > ul > li:hover, .site-navigation > ul > li > a:hover",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "Site Navigation dropdown menu",
                    "section_description"   => "This area controls the look of the site dropdown menu colors",
                    "attr_default"          => ".site-navigation > ul > li ul > li, .site-navigation > ul > li ul > li > a",
                    "attr_hover"            => ".site-navigation > ul > li  ul > li:hover, .site-navigation > ul > li  ul > li > a:hover, .site-navigation .active",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "Header v7 top bar section",
                    "section_description"   => "This area controls the look of header v7 top bar colors",
                    "attr_default"          => ".site-header__v7 :is(.topbar, .topbar__nav)",
                    "attr_hover"            => ".site-header__v7 :is(.topbar, .topbar__nav):hover",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "background-color",
                    "attr_mono"             => true,
                ],
                [
                    "section_title"         => "Header v7 top bar section texts",
                    "section_description"   => "This area controls the look of header v7 top bar color colors",
                    "attr_default"          => ".site-header__v7 :is(.topbar, .topbar__nav) .nav-item .text-dark, .site-header__v7 :is(.topbar, .topbar__nav) .nav-item :is(#basicDropdownHoverInvoker9, #basicDropdownHoverInvoker19)",
                    "attr_hover"            => ".site-header__v7 :is(.topbar, .topbar__nav) .nav-item .text-dark:hover, .site-header__v7 :is(.topbar, .topbar__nav) .nav-item :is(#basicDropdownHoverInvoker9, #basicDropdownHoverInvoker19):hover",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "color",
                    "attr_mono"             => true,
                ],
            ],
        ],
        'categories_section'             => [
            "active"                => false,
            "tab_title"             => "Custom Categories Section",
            "elements"              => [
                [
                    "section_title"         => "Mobile Card Title",
                    "section_description"   => "This color settings will affect product categories card titles",
                    "attr_default"          => ".product-categories .pc-card .card-title, .product-categories .pc-card .card-title *",
                    "attr_hover"            => ".product-categories .pc-card .card-title:hover, .product-categories .pc-card .card-title *:hover",
                    // "important_default"     => " !important",
                    // "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "Mobile Card Links",
                    "section_description"   => "This color settings will affect product categories card links (product sub category links)",
                    "attr_default"          => ".product-categories .pc-card .card-text a",
                    "attr_hover"            => ".product-categories .pc-card .card-text a:hover",
                ],
            ],
        ],
        'texts_section'             => [
            "active"                => false,
            "tab_title"             => "Bookworm Headers, BG & Texts Section",
            "elements"              => [
                [
                    "section_title"         => "Website heading 1 text",
                    "section_description"   => "This color settings will affect entire Heading 1 texts on the entire website",
                    "attr_default"          => "h1",
                    "attr_hover"            => "h1:hover",
                    // "important_default"     => " !important",
                    // "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "Website heading 2 text",
                    "section_description"   => "This color settings will affect entire Heading 2 texts on the entire website",
                    "attr_default"          => "h2",
                    "attr_hover"            => "h2:hover",
                ],
                [
                    "section_title"         => "Website heading 3 text",
                    "section_description"   => "This color settings will affect entire Heading 3 texts on the entire website",
                    "attr_default"          => "h3",
                    "attr_hover"            => "h3:hover",
                ],
                [
                    "section_title"         => "Website heading 4 text",
                    "section_description"   => "This color settings will affect entire Heading 4 texts on the entire website",
                    "attr_default"          => "h4",
                    "attr_hover"            => "h4:hover",
                ],
                [
                    "section_title"         => "Website heading 5 text",
                    "section_description"   => "This color settings will affect entire Heading 5 texts on the entire website",
                    "attr_default"          => "h5",
                    "attr_hover"            => "h5:hover",
                ],
                [
                    "section_title"         => "Website heading 6 text",
                    "section_description"   => "This color settings will affect entire Heading 6 texts on the entire website",
                    "attr_default"          => "h6",
                    "attr_hover"            => "h6:hover",
                ],
                [
                    "section_title"         => "Paragraphs text",
                    "section_description"   => "This color settings will affect app paragraph texts on the website",
                    "attr_default"          => "p",
                    "attr_hover"            => "p:hover",
                ],
            ],
        ],
        'pagebuilder_section'       => [
            "active"                => false,
            "tab_title"             => "Bookworm v3 Featured Categories Section",
            "elements"              => [
                [
                    "section_title"         => "Pagebuilder tabs",
                    "section_description"   => "This section involves setting color themes for various tab items generated by the page-builder such as products under categories and child categories",
                    "attr_default"          => ".pagebuilder-content .nav .nav-item > a, .pagebuilder-content .nav .nav-item *",
                    "attr_hover"            => ".pagebuilder-content .nav .nav-item:hover *,.pagebuilder-content .nav .nav-item a:hover *",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "Pagebuilder tabs Arrow",
                    "section_description"   => "This section involves setting color themes for tab arrow that shows which tab is active",
                    "attr_default"          => ".pagebuilder-content .nav-link-caret.active::after",
                    "attr_hover"            => ".pagebuilder-content .nav-link-caret.hover::after",
                    "attr_config"           => "border-bottom-color",
                    "attr_mono"             => true,
                ],
            ],
        ],
        'shop_section'              => [
            "active"                => false,
            "tab_title"             => "Products/Shop Pages Section",
            "elements"              => [
                [
                    "section_title"         => "Pages title section",
                    "section_description"   => "This setting will affect page titles in shop list page(s)",
                    "attr_default"          => ".page-title, .page-title *",
                    "attr_hover"            => ".page-title, .page-title *",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "color",
                    "attr_mono"             => true,
                ],
                [
                    "section_title"         => "Product breadcrumbs section",
                    "section_description"   => "Configure the color of product breadcrumbs text",
                    "attr_default"          => ".page-header .woocommerce-breadcrumb, .page-header .woocommerce-breadcrumb *",
                    "attr_hover"            => ".page-header .woocommerce-breadcrumb, .page-header .woocommerce-breadcrumb *",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "color",
                    "attr_mono"             => true,
                ],
                [
                    "section_title"         => "Product title text",
                    "section_description"   => "Configure the color of product title text",
                    "attr_default"          => ".product_title, .product_title *",
                    "attr_hover"            => ".product_title, .product_title *",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "color",
                    "attr_mono"             => true,
                ],
                [
                    "section_title"         => "Product price text",
                    "section_description"   => "Configure the color of product price text",
                    "attr_default"          => ".woocommerce-Price-amount, .woocommerce-Price-amount *",
                    "attr_hover"            => ".woocommerce-Price-amount, .woocommerce-Price-amount *",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "color",
                    "attr_mono"             => true,
                ],
                [
                    "section_title"         => "Product summary section",
                    "section_description"   => "Configure the color of product summary section",
                    "attr_default"          => ".woocommerce-product-details__short-description, .woocommerce-product-details__short-description *",
                    "attr_hover"            => ".woocommerce-product-details__short-description, .woocommerce-product-details__short-description *",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "color",
                    "attr_mono"             => true,
                ],
                [
                    "section_title"         => "Product description section",
                    "section_description"   => "Configure the color of product description section",
                    "attr_default"          => ".shop-tab-area #pills-home, .shop-tab-area #pills-home *",
                    "attr_hover"            => ".shop-tab-area #pills-home, .shop-tab-area #pills-home *",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "color",
                    "attr_mono"             => true,
                ],
            ],
        ],
        'product_inquiry_form_section'              => [
            "active"                => false,
            "tab_title"             => "Product Inquiry Form Section",
            "elements"              => [
                [
                    "section_title"         => "Modal title text",
                    "section_description"   => "Configure how the inquiry modal title text color looks like",
                    "attr_default"          => "#headerProductInquiryModal .modal-title, #productInquiryModal .modal-title, #headerProductInquiryModal .modal-title *, #productInquiryModal .modal-title *",
                    "attr_hover"            => "#headerProductInquiryModal .modal-title, #productInquiryModal .modal-title, #headerProductInquiryModal .modal-title *, #productInquiryModal .modal-title *",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "color",
                    "attr_mono"             => true,
                ],
                [
                    "section_title"         => "Inquiry form label text",
                    "section_description"   => "Configure how the inquiry form label text color looks like",
                    "attr_default"          => "#headerProductInquiryModal form label, #productInquiryModal form label, #headerProductInquiryModal form label *, #productInquiryModal form label *",
                    "attr_hover"            => "#headerProductInquiryModal form label, #productInquiryModal form label, #headerProductInquiryModal form label *, #productInquiryModal form label *",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "color",
                    "attr_mono"             => true,
                ],
                //select2-results__option select2-results__option--selectable
                //select2-results__option select2-results__option--selectable select2-results__option--highlighted
                [
                    "section_title"         => "Inquiry form products list",
                    "section_description"   => "Configure how products list color will look like",
                    "attr_default"          => "#headerProductInquiryModal form .select2-results__option select2-results__option--selectable, #productInquiryModal form .select2-results__option select2-results__option--selectable, #headerProductInquiryModal form .select2-results__option select2-results__option--selectable, #productInquiryModal form .select2-results__option select2-results__option--selectable",
                    "attr_hover"            => "#headerProductInquiryModal form .select2-results__option select2-results__option--selectable, #productInquiryModal form .select2-results__option select2-results__option--selectable, #headerProductInquiryModal form .select2-results__option select2-results__option--selectable, #productInquiryModal form .select2-results__option select2-results__option--selectable",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "Inquiry form selected products settings 1",
                    "section_description"   => "Configure how selected products text color will look like",
                    "attr_default"          => "#headerProductInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice, #productInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice, #headerProductInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice, #productInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice",
                    "attr_hover"            => "#headerProductInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice, #productInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice, #headerProductInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice, #productInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "color",
                    "attr_mono"             => true,
                ],
                [
                    "section_title"         => "Inquiry form selected products settings 2",
                    "section_description"   => "Configure how selected products background color will look like",
                    "attr_default"          => "#headerProductInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice, #productInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice, #headerProductInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice, #productInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice",
                    "attr_hover"            => "#headerProductInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice, #productInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice, #headerProductInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice, #productInquiryModal form .select2-container--default .select2-selection--multiple .select2-selection__choice",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "background-color",
                    "attr_mono"             => true,
                ],
                [
                    "section_title"         => "Inquiry form inputs",
                    "section_description"   => "Configure how the inquiry form inputs & textarea text color looks like",
                    "attr_default"          => "#headerProductInquiryModal form :is(input, textarea), #productInquiryModal form :is(input, textarea), #headerProductInquiryModal form :is(input, textarea) *, #productInquiryModal form :is(input, textarea) *",
                    "attr_hover"            => "#headerProductInquiryModal form :is(input, textarea), #productInquiryModal form :is(input, textarea), #headerProductInquiryModal form :is(input, textarea) *, #productInquiryModal form :is(input, textarea) *",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "color",
                    "attr_mono"             => true,
                ],
            ],
        ],
        'tables_section'            => [
            "active"                => false,
            "tab_title"             => "Tables Section",
            "elements"              => [
                [
                    "section_title"         => "Website tables section",
                    "section_description"   => "This color settings will affect all website table elements",
                    "attr_default"          => "table",
                    "attr_hover"            => "table:hover",
                ],
                [
                    "section_title"         => "Table Headers",
                    "section_description"   => "This color settings will affect all table headers",
                    "attr_default"          => "table thead",
                    "attr_hover"            => "table thead:hover",
                ],
                [
                    "section_title"         => "Table Body",
                    "section_description"   => "This color settings will affect all table body",
                    "attr_default"          => "table tbody",
                    "attr_hover"            => "table tbody:hover",
                ],
                [
                    "section_title"         => "Table rows",
                    "section_description"   => "This color settings will affect all table rows",
                    "attr_default"          => "table tr",
                    "attr_hover"            => "table tr:hover",
                ],
                [
                    "section_title"         => "Table cells",
                    "section_description"   => "This color settings will affect all table cells",
                    "attr_default"          => "table td",
                    "attr_hover"            => "table td:hover",
                ],
            ],
        ],
        'forms_section'            => [
            "active"                => false,
            "tab_title"             => "Forms Section",
            "elements"              => [
                [
                    "section_title"         => "Website forms section",
                    "section_description"   => "This color settings will affect all website form elements",
                    "attr_default"          => "form",
                    "attr_hover"            => "form:hover",
                ],
                [
                    "section_title"         => "Form labels",
                    "section_description"   => "This color settings will affect all form labels",
                    "attr_default"          => "label",
                    "attr_hover"            => "label:hover",
                ],
                [
                    "section_title"         => "Form inputs",
                    "section_description"   => "This color settings will affect all form elements of type input",
                    "attr_default"          => "input",
                    "attr_hover"            => "input:hover",
                ],
                [
                    "section_title"         => "Form Select Dropdown",
                    "section_description"   => "This color settings will affect all form elements of type select",
                    "attr_default"          => "select",
                    "attr_hover"            => "select:hover",
                ],
                [
                    "section_title"         => "Form Select Dropdown Options",
                    "section_description"   => "This color settings will affect all form elements of type select options",
                    "attr_default"          => "option",
                    "attr_hover"            => "option:hover",
                ],
                [
                    "section_title"         => "Form textarea fields",
                    "section_description"   => "This color settings will affect all form elements of type textarea",
                    "attr_default"          => "textarea",
                    "attr_hover"            => "textarea:hover",
                ],
            ],
        ],
        'footer_section'            => [
            "active"                => false,
            "tab_title"             => "Bookworm All Footers Section",
            "elements"              => [
                [
                    "section_title"         => "Website footer section headers/titles",
                    "section_description"   => "This color settings will affect all website footer section title text colors",
                    "attr_default"          => "footer :is(h1, h2, h3, h4), footer :is(h4, h5).text-white",
                    "attr_hover"            => "footer :is(h1, h2, h3, h4):hover, footer :is(h4, h5).text-white:hover",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "Website footer section",
                    "section_description"   => "This color settings will affect all website footer colors",
                    "attr_default"          => "footer, footer div:not(.changeLanguage *, .changeCountry *, .changeCurrency *), footer div p, footer div address *, footer .text-gray-450",
                    "attr_hover"            => "footer:hover, footer div:not(.changeLanguage *, .changeCountry *, .changeCurrency *):hover, footer div p:hover, footer div address *:hover, footer .text-gray-450",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "Footer links",
                    "section_description"   => "This color settings will affect all footer links colors",
                    "attr_default"          => "footer a:not(.dropdown-item), footer a:not(.dropdown-item) *",
                    "attr_hover"            => "footer a:not(.dropdown-item):hover, footer a:not(.dropdown-item) *:hover",
                ],
                [
                    "section_title"         => "Footer dropdown selector",
                    "section_description"   => "This color settings will affect all footer dropdown selectors colors",
                    "attr_default"          => "footer :is(.changeLanguage, .changeCountry, .changeCurrency) button.dropdown-toggle, footer :is(.changeLanguage, .changeCountry, .changeCurrency) button.dropdown-toggle:is(.text-white-60)",
                    "attr_hover"            => "footer :is(.changeLanguage, .changeCountry, .changeCurrency) button.dropdown-toggle:hover, footer :is(.changeLanguage, .changeCountry, .changeCurrency) button.dropdown-toggle:is(.text-white-60):hover",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                ],
                [
                    "section_title"         => "Footer dropdown selector open background",
                    "section_description"   => "This color settings will affect all footer dropdown open state background color",
                    "attr_default"          => "footer :is(.changeLanguage, .changeCountry, .changeCurrency) .dropdown-menu",
                    "attr_hover"            => "footer :is(.changeLanguage, .changeCountry, .changeCurrency) .dropdown-menu",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                    "attr_config"           => "background-color",
                    "attr_mono"             => true,
                ],
                [
                    "section_title"         => "Footer dropdown selector options",
                    "section_description"   => "This color settings will affect all footer dropdown selector option colors",
                    "attr_default"          => "footer :is(.changeLanguage, .changeCountry, .changeCurrency) .dropdown-menu :is(li *)",
                    "attr_hover"            => "footer :is(.changeLanguage, .changeCountry, .changeCurrency) .dropdown-menu :is(li):hover *",
                    "important_default"     => " !important",
                    "important_hover"       => " !important",
                ],
            ],
        ],
    ];

    // public function getColorSelectionsAttribute()
    // {
    //     return collect($this->COLOR_SELECTIONS);
    // }
}
