on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
      	port: 22
      	protocol: ftps
        server: 103.50.161.248
        username: ignatius2
        password: ${{ secrets.ftp_password }}
        server_dir: /var/www/vhosts/angelbookhouse.com/httpdocs/

